#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AzureStorageBrowser.Resource", IsApplication=true)]

namespace AzureStorageBrowser
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Microsoft.IdentityModel.Clients.ActiveDirectory.Resource.Id.agentWebView = global::AzureStorageBrowser.Resource.Id.agentWebView;
			global::Microsoft.IdentityModel.Clients.ActiveDirectory.Resource.Layout.WebAuthenticationBroker = global::AzureStorageBrowser.Resource.Layout.WebAuthenticationBroker;
			global::Microsoft.IdentityModel.Clients.ActiveDirectory.Resource.String.ApplicationName = global::AzureStorageBrowser.Resource.String.ApplicationName;
			global::Splat.Resource.String.library_name = global::AzureStorageBrowser.Resource.String.library_name;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int azure_storage_browser = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070006
			public const int accounts = 2131165190;
			
			// aapt resource value: 0x7f07000e
			public const int agentWebView = 2131165198;
			
			// aapt resource value: 0x7f070001
			public const int blobImageView = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int blobTextView = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int blobs = 2131165187;
			
			// aapt resource value: 0x7f070000
			public const int containers = 2131165184;
			
			// aapt resource value: 0x7f070007
			public const int goto_blobs = 2131165191;
			
			// aapt resource value: 0x7f070009
			public const int goto_queues = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int goto_tables = 2131165192;
			
			// aapt resource value: 0x7f070004
			public const int homeimage = 2131165188;
			
			// aapt resource value: 0x7f070005
			public const int login = 2131165189;
			
			// aapt resource value: 0x7f07000f
			public const int logout = 2131165199;
			
			// aapt resource value: 0x7f07000b
			public const int messages = 2131165195;
			
			// aapt resource value: 0x7f07000a
			public const int queues = 2131165194;
			
			// aapt resource value: 0x7f07000d
			public const int tablelayout = 2131165197;
			
			// aapt resource value: 0x7f07000c
			public const int tables = 2131165196;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int Blob = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int BlobDetail = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Main = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Queue = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int QueueDetail = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int Table = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int TableDetail = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int WebAuthenticationBroker = 2130968583;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f060000
			public const int Settings = 2131099648;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int app_name = 2131034118;
			
			// aapt resource value: 0x7f050000
			public const int library_name = 2131034112;
			
			// aapt resource value: 0x7f050004
			public const int login = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int logout = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int password = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int username = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
